// Curated 5-letter word list shared by both modes. Lowercase, exactly 5 letters.
// Kept intentionally small/common for the MVP; expand or swap per difficulty later.
export const WORDS: readonly string[] = [
  "about", "above", "actor", "acute", "adapt", "adept", "adult", "agent", "agile", "alarm",
  "album", "alert", "alike", "alive", "allow", "alone", "amber", "angel", "anger", "angle",
  "apple", "apply", "april", "arena", "argue", "arise", "armor", "aroma", "array", "arrow",
  "asset", "audio", "avoid", "awake", "award", "aware", "badge", "baker", "basic", "beach",
  "beard", "beast", "begin", "being", "berry", "birth", "black", "blade", "blame", "blank",
  "blast", "blaze", "blend", "blind", "block", "bloom", "board", "boost", "brain", "brake",
  "brave", "bread", "break", "brick", "bride", "brief", "bring", "broad", "brown", "brush",
  "build", "burst", "cabin", "cable", "candy", "cargo", "carry", "catch", "cause", "chain",
  "chair", "chalk", "charm", "chart", "chase", "cheap", "check", "chess", "chest", "chief",
  "child", "chord", "civic", "civil", "claim", "clash", "class", "clean", "clear", "clerk",
  "click", "cliff", "climb", "clock", "close", "cloth", "cloud", "coach", "coast", "could",
  "court", "cover", "craft", "crash", "crazy", "cream", "crest", "crime", "crisp", "cross",
  "crowd", "crown", "crust", "cycle", "daily", "dance", "delta", "dense", "depth", "diary",
  "dirty", "dozen", "draft", "drama", "drawn", "dream", "dress", "drift", "drink", "drive",
  "eagle", "early", "earth", "eight", "elite", "empty", "enemy", "enjoy", "enter", "entry",
  "equal", "error", "event", "every", "exact", "exist", "extra", "fable", "faith", "false",
  "fancy", "fault", "favor", "feast", "fence", "fever", "field", "fiber", "fight", "final",
  "flame", "flash", "fleet", "flesh", "float", "flood", "floor", "flour", "fluid", "focus",
  "force", "forge", "forty", "found", "frame", "fresh", "front", "frost", "fruit", "funny",
  "ghost", "giant", "given", "glass", "globe", "glory", "grace", "grade", "grain", "grand",
  "grant", "grape", "graph", "grasp", "grass", "grave", "great", "green", "greet", "grief",
  "group", "guard", "guess", "guest", "guide", "habit", "happy", "harsh", "haste", "heart",
  "heavy", "hedge", "hello", "hobby", "honey", "honor", "horse", "hotel", "house", "human",
  "humor", "ideal", "image", "index", "inner", "input", "irony", "issue", "ivory", "joint",
  "judge", "juice", "knife", "knock", "known", "label", "labor", "lance", "large", "laser",
  "later", "laugh", "layer", "learn", "lease", "least", "leave", "legal", "lemon", "level",
  "light", "limit", "linen", "liver", "lobby", "local", "logic", "loose", "lover", "lower",
  "loyal", "lucky", "lunar", "lunch", "magic", "major", "maker", "march", "match", "mayor",
  "medal", "media", "metal", "meter", "midst", "might", "minor", "mixed", "model", "money",
  "month", "moral", "motor", "mount", "mouse", "mouth", "movie", "music", "naval", "nerve",
  "never", "newly", "night", "noble", "noise", "north", "novel", "nurse", "ocean", "offer",
  "olive", "onion", "order", "other", "ought", "outer", "owner", "paint", "panel", "paper",
  "party", "pasta", "patch", "pause", "peace", "pearl", "phase", "phone", "photo", "piano",
  "piece", "pilot", "pitch", "pixel", "place", "plain", "plane", "plant", "plate", "plaza",
  "point", "polar", "porch", "pound", "power", "press", "price", "pride", "prime", "prose",
  "print", "prior", "prize", "proof", "proud", "prove", "pulse", "punch", "pupil", "queen",
  "query", "quest", "quick", "quiet", "quill", "quote", "radar", "radio", "raise", "rally",
  "ranch", "range", "rapid", "ratio", "razor", "reach", "react", "ready", "realm", "rebel",
  "refer", "relax", "reply", "rider", "ridge", "rifle", "right", "rigid", "rival", "river",
  "roast", "robot", "rocky", "roman", "rough", "round", "route", "royal", "rugby", "ruler",
  "rural", "salad", "salty", "sauce", "scale", "scarf", "scene", "scope", "score", "scout",
  "scrap", "sense", "serve", "seven", "shade", "shake", "shape", "share", "shark", "sharp",
  "sheep", "sheet", "shelf", "shell", "shift", "shine", "shirt", "shock", "shoot", "shore",
  "short", "shout", "shown", "sight", "silly", "since", "siren", "sixth", "skate", "skill",
  "skirt", "skull", "slate", "sleep", "slice", "slide", "slope", "small", "smart", "smile",
  "smoke", "snake", "sneak", "solar", "solid", "solve", "sorry", "sound", "south", "space",
  "spare", "spark", "speak", "speed", "spell", "spend", "spice", "spike", "spine", "spire",
  "spoke", "sport", "spray", "squad", "stack", "staff", "stage", "stain", "stair", "stake",
  "stamp", "stand", "stare", "start", "state", "steam", "steel", "steep", "steer", "stern",
  "stick", "stiff", "still", "sting", "stock", "stone", "stool", "store", "storm", "story",
  "stove", "stray", "strip", "study", "stuff", "stunt", "style", "sugar", "suite", "sunny",
  "super", "swarm", "sweet", "swift", "swing", "sword", "table", "taste", "teach", "tease",
  "tempo", "tenth", "thank", "theft", "theme", "there", "thick", "thief", "thing", "think",
  "third", "those", "three", "throw", "thumb", "tiger", "tight", "title", "toast", "today",
  "token", "tooth", "topic", "torch", "total", "touch", "tough", "tower", "toxic", "trace",
  "track", "trade", "trail", "train", "trait", "treat", "trend", "trial", "tribe", "trick",
  "troop", "trout", "truck", "truly", "trust", "truth", "tulip", "tutor", "twice", "twist",
  "ultra", "uncle", "under", "union", "unify", "unite", "unity", "until", "upper", "upset",
  "urban", "usage", "usual", "vague", "valid", "value", "valve", "vapor", "vault", "venue",
  "verse", "video", "villa", "vinyl", "viral", "virus", "visit", "vital", "vivid", "vocal",
  "voice", "voter", "wagon", "waist", "waste", "watch", "water", "weary", "weave", "wedge",
  "weird", "whale", "wheat", "wheel", "where", "which", "while", "white", "whole", "whose",
  "widen", "width", "windy", "witch", "woman", "world", "worry", "worse", "worst", "worth",
  "would", "wound", "woven", "wrist", "write", "wrong", "yacht", "yield", "young", "youth",
];

// Deterministic pick by index (wraps). Used by daily-seed and roguelike RNG alike.
export function wordAt(index: number): string {
  const len = WORDS.length;
  return WORDS[((index % len) + len) % len];
}
